### PR TITLE
ovirt_vm: fix cd_iso get all disks from storage domains

### PR DESCRIPTION
**Pull request by mnecas**
Fixes: https://github.com/oVirt/ovirt-ansible-collection/issues/62
Issue: in 4.3 the disks from ISO storage domain were not able to get from disks_service to make it backward compatible did need to gather all storage domains
@mwperina @dangel101

### CODE REVIEW

**Comment by mwperina** [comment]
Eyal, could you please also take a look?

@shenitzky

**Comment by n0p90** [comment]
@mnecas Thanks for the patch.
Unfortunately, this does not work on oVirt 4.3. It crashes with the following stack trace:
```
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_vm_payload_t_4z7zcm/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py", line 2488, in main
  File "/tmp/ansible_ovirt_vm_payload_t_4z7zcm/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1632, in post_present
  File "/tmp/ansible_ovirt_vm_payload_t_4z7zcm/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1712, in _attach_cd
  File "/tmp/ansible_ovirt_vm_payload_t_4z7zcm/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1697, in __get_cd_id
  File "/tmp/ansible_ovirt_vm_payload_t_4z7zcm/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1686, in __get_cds_from_sds
  File "/usr/local/lib64/python3.7/site-packages/ovirt_engine_sdk_python-4.3.3-py3.7-linux-x86_64.egg/ovirtsdk4/__init__.py", line 769, in follow_link
    href = obj.href
AttributeError: 'NoneType' object has no attribute 'href'
```

- `sd.disks` is an empty `ovirtsdk4.List` for _Data_ domains, despite containing many disks, including ISO
- `sd.disks` is `None` for _ISO_ domains, which causes the crash

**Comment by mnecas** [comment]
yeah currently this is working in progress
there are 2 other issues

**Comment by mnecas** [comment]
@n0p90 could you please try it on 4.3?
Thanks for your help!

**Comment by n0p90** [comment]
@mnecas 
`sd.disks` is `None` for ISO domains. This means that the following exception will always be raised when trying to use an ISO from an ISO storage:
https://github.com/oVirt/ovirt-ansible-collection/blob/a9b1f3894f9c048766c6f18ce07246194c7f1e62/plugins/modules/ovirt_vm.py#L1677

Here is a patch to make it work on oVirt 4.3, I'll let you check if it also works on oVirt 4.4:
```diff
diff --git a/plugins/modules/ovirt_vm.py b/plugins/modules/ovirt_vm.py
index 23a939b..8bcee47 100644
--- a/plugins/modules/ovirt_vm.py
+++ b/plugins/modules/ovirt_vm.py
@@ -1662,10 +1662,17 @@ class VmsModule(BaseModule):
 
     def __get_cds_from_sds(self, sds):
         for sd in sds:
-            if sd.disks is None:
+            if sd.type == otypes.StorageDomainType.ISO:
+                disks = sd.files
+                is_iso = lambda x: True
+            elif sd.type == otypes.StorageDomainType.DATA:
+                disks = sd.disks
+                is_iso = lambda x: x.content_type == otypes.DiskContentType.ISO
+            else:
+                # is there any other storage type from which ISO can be loaded?
                 continue
-            disks = list(filter(lambda x: (x.name == self.param('cd_iso') or x.id == self.param('cd_iso')) and x.content_type == otypes.DiskContentType.ISO,
-                                self._connection.follow_link(sd.disks)))
+            disks = list(filter(lambda x: (x.name == self.param('cd_iso') or x.id == self.param('cd_iso')) and is_iso(x),
+                                self._connection.follow_link(disks)))
             if disks:
                 return disks
 
```

I've never used the `ovirt-image-repository` which has a `type = otypes.StorageDomainType.IMAGE`, so I don't know if it's possible to have ISOs in it. If this is the case, then the above patch needs some modifications.

Thanks!

**Comment by mnecas** [comment]
Done some investigation and turned up that my env was broken.
There was no change between 4.3 and 4.4 around the ISO domain type.
