### ISSUE TITLE
Host `refreshed` state isn't working

### ISSUE THREAD

**Issue by ombre8** [oVirt/ovirt-ansible-collection#686]
##### SUMMARY

The `refreshed` state introduced in https://github.com/oVirt/ovirt-ansible-collection/pull/673 isn't working. I assume there is something missing in the ovirt python sdk?

##### STEPS TO REPRODUCE

```yaml
  ovirt.ovirt.ovirt_host:
    auth: "{{ rhv_auth }}"
    name: "{{ rhv_vm_host }}"
    state: refreshed
```

##### ACTUAL RESULTS

```bash
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt.ovirt.ovirt_host_payload_yina8nt6/ansible_ovirt.ovirt.ovirt_host_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_host.py", line 718, in main
  File "/tmp/ansible_ovirt.ovirt.ovirt_host_payload_yina8nt6/ansible_ovirt.ovirt.ovirt_host_payload.zip/ansible_collections/ovirt/ovirt/plugins/module_utils/ovirt.py", line 825, in action
    getattr(entity_service, action)(**kwargs)
AttributeError: 'HostService' object has no attribute 'refreshed'
fatal: [offlinebackup01.be3.puzzle.ch -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      activate: true
      address: null
      check_upgrade: true
      cluster: null
      comment: null
      enroll_certificate: false
      fetch_nested: false
      force: false
      hosted_engine: null
      id: null
      iscsi: null
      kdump_integration: null
      kernel_params: null
      name: rhvh02.example.com
      nested_attributes: []
      override_display: null
      override_iptables: null
      password: null
      poll_interval: 3
      power_management_enabled: null
      public_key: false
      reboot_after_installation: null
      reboot_after_upgrade: true
      spm_priority: null
      ssh_port: null
      state: refreshed
      timeout: 600
      vgpu_placement: null
      wait: true
  msg: '''HostService'' object has no attribute ''refreshed'''
```
Thanks for your help

**Comment by mnecas** [comment]
Hi, which version of ovirt python sdk are you using?

**Comment by mnecas** [comment]
Oh no! My mistake will post a PR
